# Generated by Django 4.2.3 on 2023-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                ("eid", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("desg", models.CharField(max_length=50, null=True)),
                ("dept", models.CharField(max_length=20, null=True)),
                ("mail", models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="receipt",
            fields=[
                ("rid", models.AutoField(primary_key=True, serialize=False)),
                ("hra", models.IntegerField()),
                ("da", models.IntegerField()),
                ("net", models.IntegerField()),
                ("los", models.IntegerField()),
                ("gross", models.IntegerField()),
            ],
        ),
    ]
