# Generated by Django 4.2.3 on 2023-07-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "eid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("desg", models.CharField(max_length=50)),
                ("dept", models.CharField(max_length=20)),
                ("mail", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="receipt",
            fields=[
                (
                    "rid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("hra", models.IntegerField()),
                ("da", models.IntegerField()),
                ("net", models.IntegerField()),
                ("lop", models.IntegerField()),
                ("gross", models.IntegerField()),
            ],
        ),
    ]
