# Generated by Django 4.2.3 on 2023-07-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eid",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
