# Generated by Django 4.2.3 on 2023-08-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="uan",
        ),
    ]
