# Generated by Django 4.2.3 on 2023-07-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="month",
            field=models.CharField(default="july-20231", max_length=50),
            preserve_default=False,
        ),
    ]
