# Generated by Django 4.2.3 on 2023-08-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="dept",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="desg",
            new_name="designation",
        ),
    ]
