# Generated by Django 4.1.10 on 2023-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="id",
        ),
        migrations.AddField(
            model_name="employee",
            name="dept",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="desg",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="mail",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="eid",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
