# Generated by Django 4.2.3 on 2023-08-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0002_remove_employee_uan"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="uan",
            field=models.IntegerField(default=129436),
            preserve_default=False,
        ),
    ]
