# Generated by Django 4.2.3 on 2023-07-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0002_alter_employee_eid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="los",
            new_name="lop",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="rid",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
