# Generated by Django 4.2.3 on 2023-07-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0002_receipt_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="rid",
            field=models.ForeignKey(
                default=9046,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminuser.receipt",
            ),
            preserve_default=False,
        ),
    ]
