# Generated by Django 4.2.3 on 2023-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0002_rename_dept_employee_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
