# Generated by Django 4.2.3 on 2023-08-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0003_employee_uan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="totaldeductions",
            new_name="total_deductions",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="totalearnings",
            new_name="total_earnings",
        ),
    ]
