# Generated by Django 4.2.3 on 2023-07-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0003_employee_rid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="rid",
        ),
        migrations.AddField(
            model_name="receipt",
            name="eid",
            field=models.ForeignKey(
                default=125,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminuser.employee",
            ),
            preserve_default=False,
        ),
    ]
