# Generated by Django 4.2.3 on 2023-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0003_receipt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phoneno",
            field=models.IntegerField(default=987456321, max_length=10),
            preserve_default=False,
        ),
    ]
