# Generated by Django 4.2.3 on 2023-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0004_rename_totaldeductions_receipt_total_deductions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="basic1",
            field=models.IntegerField(default=54654),
            preserve_default=False,
        ),
    ]
