# Generated by Django 4.2.3 on 2023-08-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0005_receipt_basic1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uan',
            field=models.CharField(max_length=20),
        ),
    ]
